export default `<section class="panel">
    <div class="section-heading"><div><p class="eyebrow">SCHOOL DETAILS</p><h2>{{ school.school_name }}</h2><p class="school-meta"><code>{{ school.slug }}</code><span :class="['status', school.status === 'inactive' ? 'off' : 'on']">{{ school.status || 'active' }}</span></p></div><div class="row-actions detail-actions"><button class="secondary" type="button" @click="$emit('back')"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M19 12H5m7 7-7-7 7-7" /></svg><span>Back</span></button><button class="secondary" type="button" @click="$emit('edit')"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 20h9" /><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z" /></svg><span>Edit school</span></button></div></div>
    <form v-if="editingSchool" class="school-form edit-form" @submit.prevent="$emit('save-school')">
      <label>Name<input v-model.trim="form.school_name" required /></label><label>Email<input v-model.trim="form.email" type="email" /></label><label>Address<input v-model.trim="form.address" /></label><label>Status<select v-model="form.status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Welcome tagline<input v-model.trim="form.tagline" maxlength="120" /></label><label class="description-field">Welcome description<textarea v-model.trim="form.description" maxlength="500" rows="3"></textarea></label><div class="form-actions"><button class="secondary" type="button" @click="$emit('cancel-edit')">Cancel</button><button class="primary" type="submit" :disabled="saving">{{ saving ? 'Saving…' : 'Save changes' }}</button></div>
    </form>
    <div class="school-stats">
      <article><span>Administrators</span><strong>{{ administrators.length }}</strong><small>School admin accounts</small></article>
      <article><span>Students</span><strong>{{ school.statistics?.students ?? 0 }}</strong><small>Enrolled students</small></article>
      <article><span>Teachers</span><strong>{{ school.statistics?.teachers ?? 0 }}</strong><small>Teacher accounts</small></article>
    </div>
    <section class="branding-manager"><div><p class="eyebrow">PORTAL BRANDING</p><h3>School images</h3><p class="muted">JPEG, PNG, or WebP up to 5 MB. Images load privately through the school portal.</p></div><div class="branding-upload-grid"><label>School logo<input type="file" accept="image/jpeg,image/png,image/webp" @change="$emit('upload-branding', 'logo', $event)" :disabled="saving" /><img v-if="school.branding?.logoKey" :src="schoolPortalUrl(school, '/api/student/school/branding/logo')" alt="Current school logo" /></label><label>Welcome image<input type="file" accept="image/jpeg,image/png,image/webp" @change="$emit('upload-branding', 'welcome-image', $event)" :disabled="saving" /><img v-if="school.branding?.welcomeImageKey" :src="schoolPortalUrl(school, '/api/student/school/branding/welcome-image')" alt="Current school welcome image" /></label></div></section>
    <div class="admins-section">
      <div class="section-heading"><div><p class="eyebrow">ACCESS</p><h2>School administrators</h2></div></div>
      <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Username</th><th>Email</th><th>Role</th><th>Actions</th></tr></thead><tbody><tr v-if="!administrators.length"><td colspan="4" class="admin-table-empty">No administrators yet.</td></tr><tr v-for="administrator in administrators" :key="administrator._id"><td><strong>{{ administrator.username }}</strong></td><td>{{ administrator.email || 'No email' }}</td><td><span class="admin-role">{{ administrator.role }}</span></td><td><button class="secondary admin-password-action" type="button" @click="$emit('start-password-reset', administrator)">Change password</button></td></tr></tbody></table></div>
      <form v-if="passwordResetAdmin" class="password-reset-form" @submit.prevent="$emit('update-password')"><div><p class="eyebrow">PASSWORD RESET</p><strong>Set a new password for {{ passwordResetAdmin.username }}</strong></div><label>New password<input :value="adminNewPassword" @input="$emit('update-admin-password', $event.target.value)" type="password" autocomplete="new-password" minlength="8" required /></label><div class="form-actions"><button class="secondary" type="button" @click="$emit('cancel-password-reset')">Cancel</button><button class="primary" type="submit" :disabled="saving || adminNewPassword.length < 8">{{ saving ? 'Saving…' : 'Update password' }}</button></div></form>
      <form class="school-form admin-form" @submit.prevent="$emit('create-administrator')"><label>Username<input v-model.trim="adminForm.username" autocomplete="off" required /></label><label>Email<input v-model.trim="adminForm.email" type="email" /></label><label>Temporary password<input v-model="adminForm.password" type="password" minlength="8" required /></label><button class="primary" type="submit" :disabled="saving">{{ saving ? 'Adding…' : 'Add administrator' }}</button></form>
    </div>
  </section>`;
